-- Insertion de données dans la table "Landlord"
INSERT INTO
    "Landlord" (
        "gender",
        "first_name",
        "last_name",
        "created_at",
        "updated_at"
    )
VALUES
    (
        'male',
        'John',
        'Doe',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Jane',
        'Smith',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'James',
        'Johnson',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Emily',
        'Williams',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'Michael',
        'Brown',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Olivia',
        'Jones',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'Daniel',
        'Taylor',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Emma',
        'Miller',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'David',
        'Wilson',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Sophia',
        'Davis',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'Joseph',
        'Anderson',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Ava',
        'Clark',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'William',
        'Thomas',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Mia',
        'Harris',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'Charles',
        'Lewis',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Grace',
        'Lee',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'Henry',
        'Martin',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Chloe',
        'Walker',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'male',
        'Samuel',
        'Hall',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'female',
        'Lily',
        'Young',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );